# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2.1"

volumes:
  poet-shared:

services:

  validator-0:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-default-0
    expose:
      - 4000
      - 5050
      - 8800
    ports:
      - "4000:4000"
      - "5050:5050"
      - "8800:8800"
    volumes:
      - poet-shared:/poet-shared
    command: "bash -c \"\
        sawadm keygen --force && \
        mkdir -p /poet-shared/validator-0 || true && \
        cp -a /etc/sawtooth/keys /poet-shared/validator-0/ && \
        while [ ! -f /poet-shared/poet-enclave-measurement ]; do sleep 1; done && \
        while [ ! -f /poet-shared/poet-enclave-basename ]; do sleep 1; done && \
        while [ ! -f /poet-shared/poet.batch ]; do sleep 1; done && \
        cp /poet-shared/poet.batch / && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=PoET \
          sawtooth.consensus.algorithm.version=0.1 \
          sawtooth.poet.report_public_key_pem=\
          \\\"$$(cat /poet-shared/simulator_rk_pub.pem)\\\" \
          sawtooth.poet.valid_enclave_measurements=$$(cat /poet-shared/poet-enclave-measurement) \
          sawtooth.poet.valid_enclave_basenames=$$(cat /poet-shared/poet-enclave-basename) \
          -o config.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
             sawtooth.poet.target_wait_time=5 \
             sawtooth.poet.initial_wait_time=25 \
             sawtooth.publisher.max_batches_per_block=100 \
          -o poet-settings.batch && \
        sawadm genesis \
          config-genesis.batch config.batch poet.batch poet-settings.batch && \
        sawtooth-validator -vvv \
          --bind network:tcp://0.0.0.0:8800 \
          --bind component:tcp://0.0.0.0:4000 \
          --bind consensus:tcp://0.0.0.0:5050 \
          --peering static \
          --endpoint tcp://validator-0:8800 \
          --scheduler parallel \
          --network-auth trust
    \""
    environment:
      PYTHONPATH: "/project/sawtooth-core/consensus/poet/common:\
        /project/sawtooth-core/consensus/poet/simulator:\
        /project/sawtooth-core/consensus/poet/core"
    stop_signal: SIGKILL

  rest-api-0:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-default-0
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: |
      bash -c "
        sawtooth-rest-api -vvvv \
          --connect tcp://validator-0:4000 \
          --bind 0.0.0.0:8000
      "
    stop_signal: SIGKILL

  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default-0
    expose:
      - 4000
    depends_on:
      - validator-0
    command: settings-tp -vvv -C tcp://validator-0:4000
    stop_signal: SIGKILL

  poet-engine-0:
    image: hyperledger/sawtooth-poet-engine:1.1
    container_name: sawtooth-poet-engine-0
    depends_on:
      - validator-0
    volumes:
      - poet-shared:/poet-shared
    command: "bash -c \"\
        if [ ! -f /poet-shared/poet-enclave-measurement ]; then \
            poet enclave measurement >> /poet-shared/poet-enclave-measurement; \
        fi && \
        if [ ! -f /poet-shared/poet-enclave-basename ]; then \
            poet enclave basename >> /poet-shared/poet-enclave-basename; \
        fi && \
        if [ ! -f /poet-shared/simulator_rk_pub.pem ]; then \
            cp /etc/sawtooth/simulator_rk_pub.pem /poet-shared; \
        fi && \
        while [ ! -f /poet-shared/validator-0/keys/validator.priv ]; do sleep 1; done && \
        cp -a /poet-shared/validator-0/keys /etc/sawtooth && \
        poet registration create -k /etc/sawtooth/keys/validator.priv -o /poet-shared/poet.batch && \
        poet-engine -C tcp://validator-0:5050 --component tcp://validator-0:4000 \
    \""

  poet-validator-registry-tp-0:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.1
    container_name: sawtooth-poet-validator-registry-tp-0
    expose:
      - 4000
    depends_on:
      - validator-0
    command: poet-validator-registry-tp -C tcp://validator-0:4000
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL

  cert-tp-python-0:
    build:
      context: .
      dockerfile: cert_python/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: cert-tp-python-local:${ISOLATION_ID}
    volumes:
      - ./:/project/sawtooth-sdk-python
    container_name: cert-tp-python-local-0
    depends_on:
      - validator-0
    command: |
      bash -c "
        bin/protogen
        cd examples/cert_python
        python3 setup.py clean --all
        python3 setup.py build
        cert-tp-python -vv -C tcp://validator-0:4000
      "
    stop_signal: SIGKILL


  validator-1:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-default-1
    expose:
      - 4001
      - 5051
      - 8801
    ports:
      - "4001:4001"
      - "5051:5051"
      - "8801:8801"
    volumes:
      - poet-shared:/poet-shared
    command: |
      bash -c "
        sawadm keygen --force && \
        mkdir -p /poet-shared/validator-1 || true && \
        cp -a /etc/sawtooth/keys /poet-shared/validator-1/ && \
        sawtooth-validator -vvv \
            --bind network:tcp://0.0.0.0:8801 \
            --bind component:tcp://0.0.0.0:4001 \
            --bind consensus:tcp://0.0.0.0:5051 \
            --peering static \
            --endpoint tcp://validator-1:8801 \
            --peers tcp://validator-0:8800 \
            --scheduler parallel \
            --network-auth trust
      "
    environment:
      PYTHONPATH: "/project/sawtooth-core/consensus/poet/common:\
        /project/sawtooth-core/consensus/poet/simulator:\
        /project/sawtooth-core/consensus/poet/core"
    stop_signal: SIGKILL

  rest-api-1:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api-default-1
    expose:
      - 8001
    ports:
      - "8001:8001"
    command: |
      bash -c "
        sawtooth-rest-api -vvv\
          --connect tcp://validator-1:4001 \
          --bind 0.0.0.0:8001
      "
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: sawtooth-settings-tp-default-1
    expose:
      - 4001
    command: settings-tp -vv -C tcp://validator-1:4001
    stop_signal: SIGKILL
    depends_on:
      - validator-1

  poet-engine-1:
    image: hyperledger/sawtooth-poet-engine:1.1
    container_name: sawtooth-poet-engine-1
    depends_on:
      - validator-1
    volumes:
      - poet-shared:/poet-shared
    command: "bash -c \"\
        while [ ! -f /poet-shared/validator-1/keys/validator.priv ]; do sleep 1; done && \
        cp -a /poet-shared/validator-1/keys /etc/sawtooth && \
        poet-engine -C tcp://validator-1:5051 --component tcp://validator-1:4001 \
    \""

  poet-validator-registry-tp-1:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.1
    container_name: sawtooth-poet-validator-registry-tp-1
    expose:
      - 4001
    depends_on:
      - validator-1
    command: poet-validator-registry-tp -C tcp://validator-1:4001
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL

  cert-tp-python-1:
    build:
      context: .
      dockerfile: cert_python/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: cert-tp-python-local:${ISOLATION_ID}
    volumes:
      - ./:/project/sawtooth-sdk-python
    container_name: cert-tp-python-local-1
    depends_on:
      - validator-1
    command: |
      bash -c "
        bin/protogen
        cd examples/cert_python
        python3 setup.py clean --all
        python3 setup.py build
        cert-tp-python -vv -C tcp://validator-1:4001
      "
    stop_signal: SIGKILL
